version: "3"
services:
  web-app:
    build:
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./fin_proj:/fin_proj
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database

    command: python3 manage.py runserver 0.0.0.0:8000
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass