# Generated by Django 4.2.7 on 2023-12-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.IntegerField()),
                ('type', models.TextField()),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ACLN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('figure', models.ImageField(upload_to='fig/')),
                ('speed', models.IntegerField()),
                ('rpm', models.IntegerField()),
                ('programm', models.TextField()),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='details.instrument')),
            ],
        ),
    ]
